"""initial professional schema

Revision ID: 8a51f746087f
Revises:
Create Date: 2026-09-28 16:35:03.375547
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = "8a51f746087f"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "airports",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("iata_code", sa.String(length=3), nullable=False),
        sa.Column("icao_code", sa.String(length=4), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("city", sa.String(length=120), nullable=False),
        sa.Column("state", sa.String(length=2), nullable=False),
        sa.Column("region", sa.String(length=80), nullable=False),
        sa.Column("latitude", sa.Float(), nullable=True),
        sa.Column("longitude", sa.Float(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_airports_iata_code"), "airports", ["iata_code"], unique=True)
    op.create_index(op.f("ix_airports_icao_code"), "airports", ["icao_code"], unique=True)
    op.create_table(
        "app_users",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("supabase_user_id", sa.String(length=36), nullable=False),
        sa.Column("email", sa.String(length=320), nullable=False),
        sa.Column("is_allowed", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("last_login_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_app_users_email"), "app_users", ["email"], unique=True)
    op.create_index(op.f("ix_app_users_supabase_user_id"), "app_users", ["supabase_user_id"], unique=True)
    op.create_table(
        "data_sources",
        sa.Column("id", sa.String(length=80), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("publisher", sa.String(length=255), nullable=False),
        sa.Column("url", sa.Text(), nullable=False),
        sa.Column("license", sa.String(length=255), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "ingestion_runs",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("provider", sa.String(length=80), nullable=False),
        sa.Column("status", sa.String(length=30), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("records_processed", sa.Integer(), nullable=False),
        sa.Column("error_summary", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_ingestion_runs_provider"), "ingestion_runs", ["provider"], unique=False)
    op.create_table(
        "operational_events",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("airport_code", sa.String(length=4), nullable=False),
        sa.Column("source_id", sa.String(length=80), nullable=False),
        sa.Column("event_type", sa.String(length=80), nullable=False),
        sa.Column("status", sa.String(length=80), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("ended_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_operational_events_airport_code"), "operational_events", ["airport_code"], unique=False)
    op.create_table(
        "provider_cache",
        sa.Column("key", sa.String(length=255), nullable=False),
        sa.Column("provider", sa.String(length=80), nullable=False),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("key"),
    )
    op.create_index(op.f("ix_provider_cache_expires_at"), "provider_cache", ["expires_at"], unique=False)
    op.create_index(op.f("ix_provider_cache_provider"), "provider_cache", ["provider"], unique=False)
    op.create_table(
        "regional_indicators",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("region_key", sa.String(length=30), nullable=False),
        sa.Column("source_id", sa.String(length=80), nullable=False),
        sa.Column("indicator", sa.String(length=100), nullable=False),
        sa.Column("value", sa.Float(), nullable=False),
        sa.Column("unit", sa.String(length=40), nullable=False),
        sa.Column("observed_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_regional_indicators_region_key"), "regional_indicators", ["region_key"], unique=False)
    op.create_table(
        "airport_aliases",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("airport_id", sa.String(length=36), nullable=False),
        sa.Column("alias", sa.String(length=120), nullable=False),
        sa.ForeignKeyConstraint(["airport_id"], ["airports.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("airport_id", "alias"),
    )
    op.create_index(op.f("ix_airport_aliases_airport_id"), "airport_aliases", ["airport_id"], unique=False)
    op.create_index(op.f("ix_airport_aliases_alias"), "airport_aliases", ["alias"], unique=False)
    op.create_table(
        "auth_audit_events",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("user_id", sa.String(length=36), nullable=True),
        sa.Column("event_type", sa.String(length=50), nullable=False),
        sa.Column("result", sa.String(length=30), nullable=False),
        sa.Column("request_id", sa.String(length=128), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["app_users.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_auth_audit_events_user_id"), "auth_audit_events", ["user_id"], unique=False)
    op.create_table(
        "conversations",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("user_id", sa.String(length=36), nullable=False),
        sa.Column("title", sa.String(length=160), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["app_users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_conversations_user_id"), "conversations", ["user_id"], unique=False)
    op.create_table(
        "facility_snapshots",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("airport_id", sa.String(length=36), nullable=False),
        sa.Column("source_id", sa.String(length=80), nullable=False),
        sa.Column("observed_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.ForeignKeyConstraint(
            ["airport_id"],
            ["airports.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_facility_snapshots_airport_id"), "facility_snapshots", ["airport_id"], unique=False)
    op.create_table(
        "route_metrics",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("origin_airport_id", sa.String(length=36), nullable=False),
        sa.Column("destination_code", sa.String(length=4), nullable=False),
        sa.Column("metric", sa.String(length=100), nullable=False),
        sa.Column("value", sa.Float(), nullable=False),
        sa.Column("unit", sa.String(length=40), nullable=False),
        sa.Column("observed_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["origin_airport_id"],
            ["airports.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_route_metrics_destination_code"), "route_metrics", ["destination_code"], unique=False)
    op.create_index(op.f("ix_route_metrics_origin_airport_id"), "route_metrics", ["origin_airport_id"], unique=False)
    op.create_table(
        "source_snapshots",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("source_id", sa.String(length=80), nullable=False),
        sa.Column("observed_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("fetched_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("checksum", sa.String(length=64), nullable=True),
        sa.Column("metadata_json", sa.JSON(), nullable=False),
        sa.ForeignKeyConstraint(
            ["source_id"],
            ["data_sources.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_source_snapshots_source_id"), "source_snapshots", ["source_id"], unique=False)
    op.create_table(
        "airport_metrics",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("airport_id", sa.String(length=36), nullable=False),
        sa.Column("source_snapshot_id", sa.String(length=36), nullable=True),
        sa.Column("metric", sa.String(length=100), nullable=False),
        sa.Column("value", sa.Float(), nullable=False),
        sa.Column("unit", sa.String(length=40), nullable=False),
        sa.Column("period_start", sa.DateTime(timezone=True), nullable=False),
        sa.Column("period_end", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["airport_id"],
            ["airports.id"],
        ),
        sa.ForeignKeyConstraint(
            ["source_snapshot_id"],
            ["source_snapshots.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("airport_id", "metric", "period_start", "period_end"),
    )
    op.create_index(op.f("ix_airport_metrics_airport_id"), "airport_metrics", ["airport_id"], unique=False)
    op.create_table(
        "llm_runs",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("conversation_id", sa.String(length=36), nullable=True),
        sa.Column("provider", sa.String(length=80), nullable=False),
        sa.Column("model", sa.String(length=120), nullable=False),
        sa.Column("purpose", sa.String(length=40), nullable=False),
        sa.Column("status", sa.String(length=30), nullable=False),
        sa.Column("latency_ms", sa.Integer(), nullable=True),
        sa.Column("input_tokens", sa.Integer(), nullable=True),
        sa.Column("output_tokens", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["conversation_id"], ["conversations.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_llm_runs_conversation_id"), "llm_runs", ["conversation_id"], unique=False)
    op.create_table(
        "messages",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("conversation_id", sa.String(length=36), nullable=False),
        sa.Column("role", sa.String(length=20), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("evidence", sa.JSON(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["conversation_id"], ["conversations.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_messages_conversation_id"), "messages", ["conversation_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_messages_conversation_id"), table_name="messages")
    op.drop_table("messages")
    op.drop_index(op.f("ix_llm_runs_conversation_id"), table_name="llm_runs")
    op.drop_table("llm_runs")
    op.drop_index(op.f("ix_airport_metrics_airport_id"), table_name="airport_metrics")
    op.drop_table("airport_metrics")
    op.drop_index(op.f("ix_source_snapshots_source_id"), table_name="source_snapshots")
    op.drop_table("source_snapshots")
    op.drop_index(op.f("ix_route_metrics_origin_airport_id"), table_name="route_metrics")
    op.drop_index(op.f("ix_route_metrics_destination_code"), table_name="route_metrics")
    op.drop_table("route_metrics")
    op.drop_index(op.f("ix_facility_snapshots_airport_id"), table_name="facility_snapshots")
    op.drop_table("facility_snapshots")
    op.drop_index(op.f("ix_conversations_user_id"), table_name="conversations")
    op.drop_table("conversations")
    op.drop_index(op.f("ix_auth_audit_events_user_id"), table_name="auth_audit_events")
    op.drop_table("auth_audit_events")
    op.drop_index(op.f("ix_airport_aliases_alias"), table_name="airport_aliases")
    op.drop_index(op.f("ix_airport_aliases_airport_id"), table_name="airport_aliases")
    op.drop_table("airport_aliases")
    op.drop_index(op.f("ix_regional_indicators_region_key"), table_name="regional_indicators")
    op.drop_table("regional_indicators")
    op.drop_index(op.f("ix_provider_cache_provider"), table_name="provider_cache")
    op.drop_index(op.f("ix_provider_cache_expires_at"), table_name="provider_cache")
    op.drop_table("provider_cache")
    op.drop_index(op.f("ix_operational_events_airport_code"), table_name="operational_events")
    op.drop_table("operational_events")
    op.drop_index(op.f("ix_ingestion_runs_provider"), table_name="ingestion_runs")
    op.drop_table("ingestion_runs")
    op.drop_table("data_sources")
    op.drop_index(op.f("ix_app_users_supabase_user_id"), table_name="app_users")
    op.drop_index(op.f("ix_app_users_email"), table_name="app_users")
    op.drop_table("app_users")
    op.drop_index(op.f("ix_airports_icao_code"), table_name="airports")
    op.drop_index(op.f("ix_airports_iata_code"), table_name="airports")
    op.drop_table("airports")
    # ### end Alembic commands ###
